version: '3.8'

services:
  backend:
    image: ghcr.io/thoriqakbar0/simkit:latest
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/simkit
    depends_on:
      - db
    expose:
      - "8000"

  frontend:
    image: ghcr.io/thoriqakbar0/simkit:latest
    ports:
      - "5173:3002"
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simkit
    expose:
      - "5432"
