version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8000" 

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3005"
    depends_on:
      - backend